image:
  - Visual Studio 2019

cache:
  - c:\users\appveyor\clcache
  - c:\local\boost_1_69_0

environment:
  BOOST_ROOT: C:\local\boost_1_69_0
  BOOST_LIBRARYDIR: C:\local\boost_1_69_0\lib64-msvc-14

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%
  - pip install clcache

before_build:
  - clcache -s

install:
  - ps: Write-Host "Checking for Boost 1.69.0 x64...";$boostdir  = Test-Path $Env:BOOST_ROOT;If ($boostdir -eq $False) {Write-Host "Downloading Boost 1.69.0 x64...";$exePath = "$Env:TEMP\boost_1_69_0-msvc-14.1-64.exe";(New-Object Net.WebClient).DownloadFile('https://bintray.com/boostorg/release/download_file?file_path=1.69.0%2Fbinaries%2Fboost_1_69_0-msvc-14.1-64.exe', $exePath);Write-Host "Installing Boost 1.69.0 x64...";cmd /c start /wait "$exePath" /verysilent;del $exePath};Write-Host "Boost 1.69.0 x64 installed!" -ForegroundColor Green

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2019 Win64" .. -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64
  - MSBuild Catalyst.sln /p:CLToolExe=clcache.exe /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m
  - src\Release\cryptotest.exe

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir catalyst-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe catalyst-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE catalyst-%APPVEYOR_REPO_TAG_NAME%
  - 7z a catalyst-%APPVEYOR_REPO_TAG_NAME%-windows.zip catalyst-%APPVEYOR_REPO_TAG_NAME%
  - copy catalyst-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: catalyst-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: CatalystRelease

deploy:
  - provider: GitHub
    auth_token:
      secure: KFrN1rc9FJN3BEoX99whHEuK5iPHHLmDcZ1Ac7tgT9oR6AxyjL0B+XMQu4wqo+fK
    artifact: CatalystRelease
    draft: false
    prerelease: false
    on:
      appveyor_repo_name: catalystdevelopment/catalyst
      appveyor_repo_tag: true

  - provider: S3
    access_key_id:
      secure: nVmSNpabdw1WcGdTTzxAEjza8j9icu89oyXbC8fZVuM=
    secret_access_key:
      secure: TpCxPp5npMRclcwHB3dhkd9ZsEgKstS6HOnQ1VR6YObEsaPyl5dr16ZdbsOgjykj
    bucket: catalyst
    region: us-east-2
    set_public: true
    folder: catalyst
    artifact: CatalystRelease
    on:
      appveyor_repo_name: catalystdevelopment/catalyst
